version: '3.4'

services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DBUSER=${POSTGRES_USER}
      - DBPASS=${POSTGRES_PASSWORD}
      - DBHOST=db
      - DBPORT=5432
      - DBNAME=${POSTGRES_DB}
  db:
    image: postgres:10
    env_file: .env  
    ports:
      - "5432:5432"
    